# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 00:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('is_winner', models.BooleanField(default=False, verbose_name='Победитель?')),
                ('when_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'ordering': ('-is_winner',),
            },
        ),
        migrations.CreateModel(
            name='GroupCandidates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='candidates.GroupCandidates', verbose_name='Група'),
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together=set([('name', 'group')]),
        ),
    ]
